on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 45 18 * * *
name: Semgrep
jobs:
  build:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - name: Use Node.js for npm 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4
    - run: npm install
    - uses: actions/checkout@v3
    - run: semgrep ci
